variavel = input('Informe alguma coisa')
print('Essa váriavel é do tipo {}'.format(type(variavel)))
print('Essa váriavel é estaços {}'.format(variavel.isspace()))
print('Essa várivel é numero {}'.format(variavel.isnumeric()))
print('Essa váriavel é letras {}'.format(variavel.isalpha()))
print('Essa várivel é capitalizada {}'.format(variavel.istitle()))
print('Essa variavel é alpha numerica (numeros e letras) {}'.format(variavel.isalnum()))
print('Essa variavel tem somente letras maiusculas {}'.format(variavel.isupper()))
print('Essa variavel tem somente letra minusculas {}'.format(variavel.islower()))

